#!/bin/bash
PARAMS=""
LINEWISE=""
while (( "$#" )); do
  case "$1" in
    -l|--linewise)
      LINEWISE="TRUE"
      shift
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS '$1'"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"

if [ ! "$1" ]; then
  echo "Usage: jipe [-l] 'javascript code'"
  exit 1
fi

TMPFILE=$(mktemp /tmp/pipe-js.js.XXXXXXXXX)
trap 'rm -f $TMPFILE' 0 2 3 15

SCRIPT=$1
if [ $LINEWISE ] ; then
	SCRIPT="_.split('\\n').forEach(_ => { $1 })"
fi

cat > "$TMPFILE" << EOM
process.stdin.setEncoding('utf8');

let _ = '';
let log = console.log.bind(console);
let write = process.stdout.write.bind(process.stdout);
let l = log;
let w = write;
let print = val => write(val + '\n');
let p = print;
let output = val => write(val + '');
let o = output;
process.stdin.on('readable', () => {
  let chunk;
  while ((chunk = process.stdin.read()) !== null) {
    _ += chunk;
  }
});

process.stdin.on('end', function () {
  if ('$LINEWISE' === 'TRUE') {
    if (_.substr(-1) === '\n') {
      _ = _.substr(0, _.length - 1);
    }
  }

  $SCRIPT
});
EOM

node "$TMPFILE"
