#!/bin/bash
TMPFILE=$(mktemp /tmp/pipe-js.js.XXXXXXXXX)
trap "rm -f $TMPFILE" 0 2 3 15

cat > "$TMPFILE" << EOM
process.stdin.setEncoding('utf8');

let _ = '';
let log = console.log.bind(console);
let write = process.stdout.write.bind(process.stdout);
let l = log;
let w = write;
process.stdin.on('readable', () => {
  let chunk;
  while ((chunk = process.stdin.read()) !== null) {
    _ += chunk;
  }
});

process.stdin.on('end', function () {
  $1
});
EOM

node "$TMPFILE"
